"""lembretes escalonados, conquistas, streak e backup

Revision ID: 3f7d9a1c5e2b
Revises: 9c1a7f2e4b6d
Create Date: 2026-07-23 23:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '3f7d9a1c5e2b'
down_revision: Union[str, None] = '9c1a7f2e4b6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'achievements',
        sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('staff_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('key', sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('staff_id', 'key', name='uq_achievement_staff_key'),
    )

    op.add_column('tickets', sa.Column('reminder_tier_sent', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('tickets', 'reminder_tier_sent', server_default=None)

    op.add_column('staff_stats', sa.Column('current_streak_days', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('staff_stats', sa.Column('best_streak_days', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('staff_stats', 'current_streak_days', server_default=None)
    op.alter_column('staff_stats', 'best_streak_days', server_default=None)
    op.add_column('staff_stats', sa.Column('last_streak_date', sa.Date(), nullable=True))
    op.add_column('staff_stats', sa.Column('last_bad_rating_at', sa.DateTime(timezone=True), nullable=True))

    op.add_column('guild_settings', sa.Column('backup_channel_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guild_settings', 'backup_channel_id')
    op.drop_column('staff_stats', 'last_bad_rating_at')
    op.drop_column('staff_stats', 'last_streak_date')
    op.drop_column('staff_stats', 'best_streak_days')
    op.drop_column('staff_stats', 'current_streak_days')
    op.drop_column('tickets', 'reminder_tier_sent')
    op.drop_table('achievements')
    # ### end Alembic commands ###
