"""guild settings: dashboard separado do painel, alerta de ticket novo

Revision ID: 42b18d28b82f
Revises: 7136810fcab5
Create Date: 2026-07-23 18:53:19.920734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42b18d28b82f'
down_revision: Union[str, None] = '7136810fcab5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guild_settings', sa.Column('ticket_alert_channel_id', sa.BigInteger(), nullable=True))
    op.add_column('guild_settings', sa.Column('dashboard_channel_id', sa.BigInteger(), nullable=True))
    op.add_column('guild_settings', sa.Column('dashboard_message_id', sa.BigInteger(), nullable=True))
    op.drop_column('guild_settings', 'painel_message_id')
    op.drop_column('guild_settings', 'painel_channel_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guild_settings', sa.Column('painel_channel_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('guild_settings', sa.Column('painel_message_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('guild_settings', 'dashboard_message_id')
    op.drop_column('guild_settings', 'dashboard_channel_id')
    op.drop_column('guild_settings', 'ticket_alert_channel_id')
    # ### end Alembic commands ###
