"""canal de transcricao configuravel

Revision ID: 65888546547a
Revises: af3d4f736878
Create Date: 2026-07-23 19:35:25.868404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65888546547a'
down_revision: Union[str, None] = 'af3d4f736878'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guild_settings', sa.Column('transcript_channel_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guild_settings', 'transcript_channel_id')
    # ### end Alembic commands ###
