"""fase2 core loop: staff, tickets, claims, avaliacoes, logs, config

Revision ID: 7136810fcab5
Revises: 
Create Date: 2026-07-23 17:54:49.063721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7136810fcab5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guild_settings',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('log_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('ranking_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('reports_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('evaluations_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('moderator_role_id', sa.BigInteger(), nullable=True),
    sa.Column('dev_role_id', sa.BigInteger(), nullable=True),
    sa.Column('ceo_role_id', sa.BigInteger(), nullable=True),
    sa.Column('inactive_after_minutes', sa.Integer(), nullable=True),
    sa.Column('ticket_category_id', sa.BigInteger(), nullable=True),
    sa.Column('painel_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('painel_message_id', sa.BigInteger(), nullable=True),
    sa.Column('extra_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id')
    )
    op.create_table('staff',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('discord_user_id', sa.BigInteger(), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'discord_user_id', name='uq_staff_guild_user')
    )
    op.create_table('staff_activity',
    sa.Column('staff_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('CLAIM', 'UNCLAIM', 'CLOSED', name='staff_activity_event'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('opened_by_discord_id', sa.BigInteger(), nullable=False),
    sa.Column('category', sa.Enum('BUG', 'DENUNCIA', 'DUVIDA', 'SUGESTAO', 'PARCERIA', 'OUTRO', name='ticket_category'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLAIMED', 'CLOSED', 'CANCELLED', name='ticket_status'), nullable=False),
    sa.Column('claimed_by_staff_id', sa.UUID(), nullable=True),
    sa.Column('first_response_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by_discord_id', sa.BigInteger(), nullable=True),
    sa.Column('deleted_before_service', sa.Boolean(), nullable=False),
    sa.Column('counts_for_stats', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claimed_by_staff_id'], ['staff.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id')
    )
    op.create_table('claims',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('staff_id', sa.UUID(), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('unclaimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluations',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('staff_id', sa.UUID(), nullable=False),
    sa.Column('rated_by_discord_id', sa.BigInteger(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_id')
    )
    op.create_table('logs',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.Enum('CLAIM', 'UNCLAIM', 'FECHAMENTO', 'AVALIACAO', 'RANKING_ALTERADO', 'ERRO', 'ATUALIZACAO_AUTOMATICA', 'CONFIG_ALTERADA', name='log_action'), nullable=False),
    sa.Column('actor_discord_id', sa.BigInteger(), nullable=True),
    sa.Column('staff_id', sa.UUID(), nullable=True),
    sa.Column('ticket_id', sa.UUID(), nullable=True),
    sa.Column('category_snapshot', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff_stats',
    sa.Column('staff_id', sa.UUID(), nullable=False),
    sa.Column('tickets_assumidos', sa.Integer(), nullable=False),
    sa.Column('tickets_fechados', sa.Integer(), nullable=False),
    sa.Column('tickets_cancelados', sa.Integer(), nullable=False),
    sa.Column('avaliacoes_count', sa.Integer(), nullable=False),
    sa.Column('avaliacao_media', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('melhor_avaliacao', sa.SmallInteger(), nullable=True),
    sa.Column('pior_avaliacao', sa.SmallInteger(), nullable=True),
    sa.Column('tempo_medio_primeira_resposta_s', sa.Integer(), nullable=True),
    sa.Column('tempo_medio_fechamento_s', sa.Integer(), nullable=True),
    sa.Column('primeiro_ticket_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ultimo_ticket_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ticket_atual_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_atual_id'], ['tickets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staff_id')
    )
    op.create_table('ticket_messages',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('USER_FIRST', 'STAFF_FIRST', name='ticket_message_kind'), nullable=False),
    sa.Column('discord_message_id', sa.BigInteger(), nullable=False),
    sa.Column('author_discord_id', sa.BigInteger(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discord_message_id'),
    sa.UniqueConstraint('ticket_id', 'kind', name='uq_ticket_message_kind')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_messages')
    op.drop_table('staff_stats')
    op.drop_table('logs')
    op.drop_table('evaluations')
    op.drop_table('claims')
    op.drop_table('tickets')
    op.drop_table('staff_activity')
    op.drop_table('staff')
    op.drop_table('guild_settings')
    # ### end Alembic commands ###
