"""dias ativos, recorde diario e perfect streak

Revision ID: 7a2e8c4f1d9b
Revises: 3f7d9a1c5e2b
Create Date: 2026-07-24 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a2e8c4f1d9b'
down_revision: Union[str, None] = '3f7d9a1c5e2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff_stats', sa.Column('total_active_days', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('staff_stats', sa.Column('current_day_date', sa.Date(), nullable=True))
    op.add_column('staff_stats', sa.Column('current_day_ticket_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('staff_stats', sa.Column('best_day_ticket_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('staff_stats', sa.Column('current_perfect_streak', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('staff_stats', 'total_active_days', server_default=None)
    op.alter_column('staff_stats', 'current_day_ticket_count', server_default=None)
    op.alter_column('staff_stats', 'best_day_ticket_count', server_default=None)
    op.alter_column('staff_stats', 'current_perfect_streak', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff_stats', 'current_perfect_streak')
    op.drop_column('staff_stats', 'best_day_ticket_count')
    op.drop_column('staff_stats', 'current_day_ticket_count')
    op.drop_column('staff_stats', 'current_day_date')
    op.drop_column('staff_stats', 'total_active_days')
    # ### end Alembic commands ###
