"""blacklist channel e log action spam

Revision ID: 9c1a7f2e4b6d
Revises: 65888546547a
Create Date: 2026-07-23 22:10:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c1a7f2e4b6d'
down_revision: Union[str, None] = '65888546547a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guild_settings', sa.Column('blacklist_channel_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###
    op.execute("ALTER TYPE log_action ADD VALUE IF NOT EXISTS 'spam_detectado'")
    op.execute("ALTER TYPE log_action ADD VALUE IF NOT EXISTS 'blacklist_acao'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guild_settings', 'blacklist_channel_id')
    # ### end Alembic commands ###
    # Postgres nao suporta remover valor de enum — downgrade nao reverte o ADD VALUE.
