"""ranking_message_id e log action reabertura

Revision ID: af3d4f736878
Revises: 42b18d28b82f
Create Date: 2026-07-23 19:19:24.674064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af3d4f736878'
down_revision: Union[str, None] = '42b18d28b82f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guild_settings', sa.Column('ranking_message_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###
    op.execute("ALTER TYPE log_action ADD VALUE IF NOT EXISTS 'reabertura'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guild_settings', 'ranking_message_id')
    # ### end Alembic commands ###
    # Postgres nao suporta remover valor de enum — downgrade nao reverte o ADD VALUE.
